name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
env:
  AZURE_WEBAPP_NAME: frontend-unit-core-uat
  AZURE_WEBAPP_PATH: '.'
  DOTNET_VERSION: 3.1.201

jobs:
  build-net-core:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      - 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build And Publish
      run:
        dotnet build --configuration release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PATH }}/Angular.SSR.NetCore'

    - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_UAT_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PATH }}/Angular.SSR.NetCore'